[package]
name = "gen_data"
version = "0.1.0"
authors = ["Alex Whitney <adwhit@fastmail.com>"]

[dependencies]
random = "0.12.2"
rand = "0.4.2"
rand_derive = "0.3.1"
structopt = "0.2.6"

[[bin]]
name = "gen-data"
path = "gen_data.rs"